// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyoM1N6taQYObRFT_De7rAMXP0AoPUK5E',
    appId: '1:643046244665:web:9e4e9acabb6ddb6f14a8e8',
    messagingSenderId: '643046244665',
    projectId: 'ielts-cat',
    authDomain: 'ielts-cat.firebaseapp.com',
    storageBucket: 'ielts-cat.appspot.com',
    measurementId: 'G-EVW8TFCK5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGci7ZdduSDd-oSEoIhX8-ZZ-Cay17b8E',
    appId: '1:643046244665:android:9e3232c79b01bf4714a8e8',
    messagingSenderId: '643046244665',
    projectId: 'ielts-cat',
    storageBucket: 'ielts-cat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL9ZDxmNi2BibM4U9ekiJsKeIXwwBhMH8',
    appId: '1:643046244665:ios:a221a265ed4995af14a8e8',
    messagingSenderId: '643046244665',
    projectId: 'ielts-cat',
    storageBucket: 'ielts-cat.appspot.com',
    iosBundleId: 'com.sancbyt.ieltsCat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL9ZDxmNi2BibM4U9ekiJsKeIXwwBhMH8',
    appId: '1:643046244665:ios:a221a265ed4995af14a8e8',
    messagingSenderId: '643046244665',
    projectId: 'ielts-cat',
    storageBucket: 'ielts-cat.appspot.com',
    iosBundleId: 'com.sancbyt.ieltsCat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyoM1N6taQYObRFT_De7rAMXP0AoPUK5E',
    appId: '1:643046244665:web:5340365bbec740ca14a8e8',
    messagingSenderId: '643046244665',
    projectId: 'ielts-cat',
    authDomain: 'ielts-cat.firebaseapp.com',
    storageBucket: 'ielts-cat.appspot.com',
    measurementId: 'G-DHCQ3KXJSY',
  );
}
