// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtxThUan4PRKv9KGIG_pZqc_aiA3q01uo',
    appId: '1:302292436063:web:fb4f4298aa5cbff70747ea',
    messagingSenderId: '302292436063',
    projectId: 'ielts-cat-shahednoor',
    authDomain: 'ielts-cat-shahednoor.firebaseapp.com',
    storageBucket: 'ielts-cat-shahednoor.firebasestorage.app',
    measurementId: 'G-HDN8D0K1XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2LuCJvGMRwd6UHBXpROHw-RYCdqwlCL4',
    appId: '1:302292436063:android:6004df42b30bba8d0747ea',
    messagingSenderId: '302292436063',
    projectId: 'ielts-cat-shahednoor',
    storageBucket: 'ielts-cat-shahednoor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkJLyOTbLHo0BVQNY01M4NVyoDZKPRFc0',
    appId: '1:302292436063:ios:abb283b136acaf060747ea',
    messagingSenderId: '302292436063',
    projectId: 'ielts-cat-shahednoor',
    storageBucket: 'ielts-cat-shahednoor.firebasestorage.app',
    iosBundleId: 'com.shahednoor.ieltsCat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkJLyOTbLHo0BVQNY01M4NVyoDZKPRFc0',
    appId: '1:302292436063:ios:abb283b136acaf060747ea',
    messagingSenderId: '302292436063',
    projectId: 'ielts-cat-shahednoor',
    storageBucket: 'ielts-cat-shahednoor.firebasestorage.app',
    iosBundleId: 'com.shahednoor.ieltsCat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtxThUan4PRKv9KGIG_pZqc_aiA3q01uo',
    appId: '1:302292436063:web:4cee592992c067be0747ea',
    messagingSenderId: '302292436063',
    projectId: 'ielts-cat-shahednoor',
    authDomain: 'ielts-cat-shahednoor.firebaseapp.com',
    storageBucket: 'ielts-cat-shahednoor.firebasestorage.app',
    measurementId: 'G-V0WMJ9TPZS',
  );

}