// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtxThUan4PRKv9KGIG_pZqc_aiA3q01uo',
    appId: '1:302292436063:web:37a02cc2313e029e0747ea',
    messagingSenderId: '302292436063',
    projectId: 'ielts-cat-shahednoor',
    authDomain: 'ielts-cat-shahednoor.firebaseapp.com',
    storageBucket: 'ielts-cat-shahednoor.firebasestorage.app',
    measurementId: 'G-LS0S7YR2Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2LuCJvGMRwd6UHBXpROHw-RYCdqwlCL4',
    appId: '1:302292436063:android:59b09f8accb71f830747ea',
    messagingSenderId: '302292436063',
    projectId: 'ielts-cat-shahednoor',
    storageBucket: 'ielts-cat-shahednoor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkJLyOTbLHo0BVQNY01M4NVyoDZKPRFc0',
    appId: '1:302292436063:ios:4a5bc1165f72ce2c0747ea',
    messagingSenderId: '302292436063',
    projectId: 'ielts-cat-shahednoor',
    storageBucket: 'ielts-cat-shahednoor.firebasestorage.app',
    androidClientId: '302292436063-q7peu4n1mos0qvr6t06unsd34njh7jtn.apps.googleusercontent.com',
    iosClientId: '302292436063-thr1nr26rji259fl8uonoq4r1vbe7jqh.apps.googleusercontent.com',
    iosBundleId: 'app.shahednoor.ieltscat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkJLyOTbLHo0BVQNY01M4NVyoDZKPRFc0',
    appId: '1:302292436063:ios:4a5bc1165f72ce2c0747ea',
    messagingSenderId: '302292436063',
    projectId: 'ielts-cat-shahednoor',
    storageBucket: 'ielts-cat-shahednoor.firebasestorage.app',
    androidClientId: '302292436063-q7peu4n1mos0qvr6t06unsd34njh7jtn.apps.googleusercontent.com',
    iosClientId: '302292436063-thr1nr26rji259fl8uonoq4r1vbe7jqh.apps.googleusercontent.com',
    iosBundleId: 'app.shahednoor.ieltscat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtxThUan4PRKv9KGIG_pZqc_aiA3q01uo',
    appId: '1:302292436063:web:8a3b25482dc31b820747ea',
    messagingSenderId: '302292436063',
    projectId: 'ielts-cat-shahednoor',
    authDomain: 'ielts-cat-shahednoor.firebaseapp.com',
    storageBucket: 'ielts-cat-shahednoor.firebasestorage.app',
    measurementId: 'G-VTDP205KBC',
  );
}
